version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --configuration staging
  post_build:
    commands:
      - pwd
      - aws s3 sync frontend/dist/frontend/browser s3://your-bucket-name --delete
# artifacts:
#     files:
#         - '**/*'
#     base-directory: 'frontend/dist/frontend/browser'
#     discard-paths: no