#!/bin/zsh

ANGULAR_ENVIRONMENT=production
BUCKET_NAME=www.futbal-spoluhrac.sk
CLOUDFRONT_DISTRIBUTION_ID="E3GBJRGU7JT3S8"
GOOGLE_SEARCH_CONSOLE_VERIFICATION_FILE=google3b9bed403026ef96.html

./s3_deploy.sh $ANGULAR_ENVIRONMENT $BUCKET_NAME $CLOUDFRONT_DISTRIBUTION_ID $GOOGLE_SEARCH_CONSOLE_VERIFICATION_FILE