services:
  db:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      # Where our data will be persisted
      - my-db:/var/lib/mysql
      # apply all sql files in . in order to initialize db
      - .:/docker-entrypoint-initdb.d/:ro
volumes:
  my-db: