export enum Consent {
    PLAYER_STORE_DATA = 1,
    PLAYER_PROVIDE_DATA_TO_TEAMS = 2,
    PLAYER_AGE = 3,
    PLAYER_PROVIDE_DATA_TO_THIRD_PARTIES = 4,
    TEAM_STORE_DATA = 101,
    TEAM_PROVIDE_DATA_TO_TEAMS = 102,
    TEAM_AGE = 103,
    TEAM_PROVIDE_DATA_TO_THIRD_PARTIES = 104,
}